fixes 24 image doesn't resize
social-media-app-project/social-media-app pull request #27
Opened 2022-06-04 22:43 UTC by brandhawa99

might want to look at the other option i put in the comments of  ```img.picture```

2022-06-04 22:56 UTC, rdhillon1016 requested changes

2022-06-04 22:56 UTC, rdhillon1016 commented on frontend/src/components/ImageSlideshow/Image/Image.module.css
> +    object-fit:contain;
contain is good (vertical pictures look really weird with object-fit:cover).

2022-06-04 22:56 UTC, rdhillon1016 commented on frontend/src/components/ImageSlideshow/Image/Image.module.css
> +    border-radius: 1.25rem;
border is a bit off-putting

2022-06-05 01:17 UTC, brandhawa99 commented
i fucked some shit up trying to do the squash thing

2022-06-05 01:19 UTC, closed without merging

2022-06-05 01:20 UTC, brandhawa99 commented
tried to do it from the command line